// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdTAh_G_J7_7ao13GYh8a5T8JTmYxXOUs',
    appId: '1:426704624424:web:02fb893cf29d2466128e1d',
    messagingSenderId: '426704624424',
    projectId: 'local1-e61cb',
    authDomain: 'local1-e61cb.firebaseapp.com',
    storageBucket: 'local1-e61cb.firebasestorage.app',
    measurementId: 'G-TTDB39HLEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5W6f7ImUCdtO84k8j8igQpQoddqDSSxY',
    appId: '1:426704624424:android:d2bf3156680490d2128e1d',
    messagingSenderId: '426704624424',
    projectId: 'local1-e61cb',
    storageBucket: 'local1-e61cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPp8tC3eMj6DCM7lxFlfUZMBO_WB68hzw',
    appId: '1:426704624424:ios:c21b5c40184939d9128e1d',
    messagingSenderId: '426704624424',
    projectId: 'local1-e61cb',
    storageBucket: 'local1-e61cb.firebasestorage.app',
    iosBundleId: 'com.example.localv1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPp8tC3eMj6DCM7lxFlfUZMBO_WB68hzw',
    appId: '1:426704624424:ios:c21b5c40184939d9128e1d',
    messagingSenderId: '426704624424',
    projectId: 'local1-e61cb',
    storageBucket: 'local1-e61cb.firebasestorage.app',
    iosBundleId: 'com.example.localv1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdTAh_G_J7_7ao13GYh8a5T8JTmYxXOUs',
    appId: '1:426704624424:web:1f280264408f4845128e1d',
    messagingSenderId: '426704624424',
    projectId: 'local1-e61cb',
    authDomain: 'local1-e61cb.firebaseapp.com',
    storageBucket: 'local1-e61cb.firebasestorage.app',
    measurementId: 'G-W4BRGCSQB9',
  );
}
