// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdTAh_G_J7_7ao13GYh8a5T8JTmYxXOUs',
    appId: '1:426704624424:web:02fb893cf29d2466128e1d',
    messagingSenderId: '426704624424',
    projectId: 'local1-e61cb',
    authDomain: 'local1-e61cb.firebaseapp.com',
    storageBucket: 'local1-e61cb.firebasestorage.app',
    measurementId: 'G-TTDB39HLEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5W6f7ImUCdtO84k8j8igQpQoddqDSSxY',
    appId: '1:426704624424:android:ab4c743cca4df07a128e1d',
    messagingSenderId: '426704624424',
    projectId: 'local1-e61cb',
    storageBucket: 'local1-e61cb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPp8tC3eMj6DCM7lxFlfUZMBO_WB68hzw',
    appId: '1:426704624424:ios:b9b54dbc782ef1b5128e1d',
    messagingSenderId: '426704624424',
    projectId: 'local1-e61cb',
    storageBucket: 'local1-e61cb.firebasestorage.app',
    androidClientId: '426704624424-3hgh2ba1d1r8o80mp8ounr86tog8c8gc.apps.googleusercontent.com',
    iosClientId: '426704624424-0q5hla855122090d13bu49888i43vm9d.apps.googleusercontent.com',
    iosBundleId: 'com.nearhood.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPp8tC3eMj6DCM7lxFlfUZMBO_WB68hzw',
    appId: '1:426704624424:ios:c21b5c40184939d9128e1d',
    messagingSenderId: '426704624424',
    projectId: 'local1-e61cb',
    storageBucket: 'local1-e61cb.firebasestorage.app',
    androidClientId: '426704624424-3hgh2ba1d1r8o80mp8ounr86tog8c8gc.apps.googleusercontent.com',
    iosClientId: '426704624424-h7otks6hhu62j90nc3m05p44f1fhlqra.apps.googleusercontent.com',
    iosBundleId: 'com.example.localv1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdTAh_G_J7_7ao13GYh8a5T8JTmYxXOUs',
    appId: '1:426704624424:web:3719ef63e4a09de5128e1d',
    messagingSenderId: '426704624424',
    projectId: 'local1-e61cb',
    authDomain: 'local1-e61cb.firebaseapp.com',
    storageBucket: 'local1-e61cb.firebasestorage.app',
    measurementId: 'G-TE8308W0Y7',
  );
}
